/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "Inter",
          "SF Pro Display",
          "SF Pro Text",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        display: [
          "Inter",
          "SF Pro Display",
          "system-ui",
          "-apple-system",
          "sans-serif",
        ],
        mono: [
          '"SF Mono"',
          '"Fira Code"',
          "ui-monospace",
          "monospace",
        ],
      },
      colors: {
        rausch: {
          DEFAULT: "var(--rausch)",
          active: "var(--rausch-active)",
          disabled: "var(--rausch-disabled)",
          light: "var(--rausch-light)",
        },
        ink: {
          DEFAULT: "var(--ink)",
          body: "var(--ink-body)",
          muted: "var(--ink-muted)",
          "muted-soft": "var(--ink-muted-soft)",
        },
        canvas: {
          DEFAULT: "var(--canvas)",
          soft: "var(--canvas-soft)",
          strong: "var(--canvas-strong)",
        },
        "user-bubble": "var(--user-bubble)",
        border: {
          DEFAULT: "var(--border)",
          soft: "var(--border-soft)",
          strong: "var(--border-strong)",
        },
        surface: {
          DEFAULT: "var(--canvas)",
          secondary: "var(--canvas-soft)",
          card: "var(--canvas)",
        },
        text: {
          primary: "var(--ink)",
          secondary: "var(--ink-body)",
          tertiary: "var(--ink-muted)",
          muted: "var(--ink-muted-soft)",
          inverse: "var(--canvas)",
        },
        error: {
          DEFAULT: "var(--error)",
          hover: "#b32505",
          light: "var(--error-light)",
        },
        success: {
          DEFAULT: "var(--success)",
          light: "var(--success-light)",
        },
        info: {
          DEFAULT: "var(--info)",
          light: "var(--info-light)",
        },
        warning: {
          DEFAULT: "var(--warning)",
          light: "var(--warning-light)",
        },
        link: {
          DEFAULT: "#428bff",
        },
      },
      spacing: {
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        10: "40px",
        12: "48px",
        16: "64px",
        20: "80px",
      },
      borderRadius: {
        none: "0px",
        xs: "4px",
        sm: "8px",
        md: "14px",
        lg: "20px",
        xl: "32px",
        pill: "9999px",
        full: "9999px",
      },
      fontSize: {
        "display-xl": ["28px", { lineHeight: "1.43", fontWeight: "700", letterSpacing: "0" }],
        "display-lg": ["22px", { lineHeight: "1.18", fontWeight: "500", letterSpacing: "-0.44px" }],
        "display-md": ["21px", { lineHeight: "1.43", fontWeight: "700", letterSpacing: "0" }],
        "display-sm": ["20px", { lineHeight: "1.20", fontWeight: "600", letterSpacing: "-0.18px" }],
        "title-md": ["16px", { lineHeight: "1.25", fontWeight: "600", letterSpacing: "0" }],
        "title-sm": ["16px", { lineHeight: "1.25", fontWeight: "500", letterSpacing: "0" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400", letterSpacing: "0" }],
        "body-sm": ["14px", { lineHeight: "1.43", fontWeight: "400", letterSpacing: "0" }],
        caption: ["14px", { lineHeight: "1.29", fontWeight: "500", letterSpacing: "0" }],
        "caption-sm": ["13px", { lineHeight: "1.23", fontWeight: "400", letterSpacing: "0" }],
        badge: ["11px", { lineHeight: "1.18", fontWeight: "600", letterSpacing: "0" }],
        "micro-label": ["12px", { lineHeight: "1.33", fontWeight: "700", letterSpacing: "0" }],
        "button-md": ["16px", { lineHeight: "1.25", fontWeight: "500", letterSpacing: "0" }],
        "button-sm": ["14px", { lineHeight: "1.29", fontWeight: "500", letterSpacing: "0" }],
        link: ["14px", { lineHeight: "1.43", fontWeight: "400", letterSpacing: "0" }],
        "nav-link": ["16px", { lineHeight: "1.25", fontWeight: "600", letterSpacing: "0" }],
        hero: ["56px", { lineHeight: "1.07", fontWeight: "600", letterSpacing: "-0.28px" }],
        "hero-sm": ["40px", { lineHeight: "1.1", fontWeight: "600", letterSpacing: "0" }],
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.06), 0 1px 3px rgba(0,0,0,0.1)",
        "card-hover": "0 2px 8px rgba(0,0,0,0.08), 0 4px 16px rgba(0,0,0,0.06)",
        elevated: "0 4px 12px rgba(0,0,0,0.08), 0 8px 24px rgba(0,0,0,0.04)",
        modal: "0 8px 32px rgba(0,0,0,0.12), 0 16px 64px rgba(0,0,0,0.08)",
        glow: "0 0 0 3px rgba(255,56,92,0.15)",
        "focus-ring": "0 0 0 2px var(--canvas), 0 0 0 4px var(--ink)",
      },
      animation: {
        "fade-in": "fadeIn 0.2s ease-out",
        "fade-in-up": "fadeInUp 0.3s ease-out",
        "fade-in-down": "fadeInDown 0.3s ease-out",
        "scale-in": "scaleIn 0.15s ease-out",
        "slide-in-right": "slideInRight 0.3s cubic-bezier(0.16,1,0.3,1)",
        "slide-in-left": "slideInLeft 0.3s cubic-bezier(0.16,1,0.3,1)",
        "slide-up": "slideUp 0.3s cubic-bezier(0.16,1,0.3,1)",
        "slide-down": "slideDown 0.3s cubic-bezier(0.16,1,0.3,1)",
        "scale-up": "scaleUp 0.2s cubic-bezier(0.16,1,0.3,1)",
        "scale-down": "scaleDown 0.2s cubic-bezier(0.16,1,0.3,1)",
        "bounce-in": "bounceIn 0.4s cubic-bezier(0.34,1.56,0.64,1)",
        shimmer: "shimmer 1.5s infinite",
        "pulse-soft": "pulseSoft 2s ease-in-out infinite",
        toast: "toastIn 0.4s cubic-bezier(0.16,1,0.3,1)",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeInDown: {
          "0%": { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideInRight: {
          "0%": { opacity: "0", transform: "translateX(16px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideInLeft: {
          "0%": { opacity: "0", transform: "translateX(-16px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        scaleUp: {
          "0%": { transform: "scale(0.98)" },
          "100%": { transform: "scale(1)" },
        },
        scaleDown: {
          "0%": { transform: "scale(1)" },
          "100%": { transform: "scale(0.98)" },
        },
        bounceIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        pulseSoft: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        toastIn: {
          "0%": { opacity: "0", transform: "translateY(16px) scale(0.96)" },
          "100%": { opacity: "1", transform: "translateY(0) scale(1)" },
        },
      },
      transitionTimingFunction: {
        "apple": "cubic-bezier(0.16, 1, 0.3, 1)",
        "apple-bounce": "cubic-bezier(0.34, 1.56, 0.64, 1)",
      },
      backdropBlur: {
        xs: "2px",
        glass: "20px",
      },
      backdropBrightness: {
        25: ".25",
        75: ".75",
      },
    },
  },
  plugins: [],
};
