"""create documents table

Revision ID: 130f96c2c25b
Revises: 6afc0115cdd4
Create Date: 2026-06-25 14:43:47.797933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130f96c2c25b'
down_revision: Union[str, None] = '6afc0115cdd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=500), nullable=False))
    op.drop_column('documents', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
