"""add composite indexes

Revision ID: 48a1cac159a7
Revises: fc9963d84d13
Create Date: 2026-06-30 21:12:52.028729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a1cac159a7'
down_revision: Union[str, None] = 'fc9963d84d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunks_document_order', 'chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('ix_documents_user_created', 'documents', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_documents_user_status', 'documents', ['user_id', 'status'], unique=False)
    op.create_index('ix_flashcards_user_created', 'flashcards', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memories_user_type', 'memories', ['user_id', 'memory_type'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_quiz_attempts_quiz_created', 'quiz_attempts', ['quiz_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_attempts_quiz_created', table_name='quiz_attempts')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index('ix_memories_user_type', table_name='memories')
    op.drop_index('ix_flashcards_user_created', table_name='flashcards')
    op.drop_index('ix_documents_user_status', table_name='documents')
    op.drop_index('ix_documents_user_created', table_name='documents')
    op.drop_index('ix_chunks_document_order', table_name='chunks')
    # ### end Alembic commands ###
