"""add check and unique constraints

Revision ID: 4aff9a8f9fac
Revises: 48a1cac159a7
Create Date: 2026-06-30 21:45:07.996835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aff9a8f9fac'
down_revision: Union[str, None] = '48a1cac159a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_memories_user_key', 'memories', ['user_id', 'key'])

    op.create_check_constraint(
        'ck_documents_file_size_positive',
        'documents',
        'file_size > 0',
    )

    op.create_check_constraint(
        'ck_chunks_chunk_index_non_negative',
        'chunks',
        'chunk_index >= 0',
    )

    op.create_check_constraint(
        'ck_chunks_token_count_positive',
        'chunks',
        'token_count > 0',
    )

    op.create_check_constraint(
        'ck_quiz_attempts_score_non_negative',
        'quiz_attempts',
        'score >= 0',
    )

    op.create_check_constraint(
        'ck_quiz_attempts_total_questions_positive',
        'quiz_attempts',
        'total_questions > 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_quiz_attempts_total_questions_positive', 'quiz_attempts', type_='check')
    op.drop_constraint('ck_quiz_attempts_score_non_negative', 'quiz_attempts', type_='check')
    op.drop_constraint('ck_chunks_token_count_positive', 'chunks', type_='check')
    op.drop_constraint('ck_chunks_chunk_index_non_negative', 'chunks', type_='check')
    op.drop_constraint('ck_documents_file_size_positive', 'documents', type_='check')
    op.drop_constraint('uq_memories_user_key', 'memories', type_='unique')
    # ### end Alembic commands ###
